Repository alexgul1/PM-Project-2, pull requests merged in 2021-02, with the labels that each got.

#1 added API requests
  src/js/AuthAPI.js
  src/js/CardAPI.js
  src/js/User.js
  src/js/config.js
Labels: enhancement

#4 BoardUI and ColumnUI components
  src/js/App.js
  src/js/BoardUI.js
  src/js/ColumnUI.js
  src/js/script.js
Labels: enhancement, help wanted

#5 board, modal windows templates
  .sassrc
  package-lock.json
  package.json
  src/img/delete-icon.svg
  src/img/update-icon.svg
  src/img/user-icon.svg
  src/index.html
  src/styles/board.scss
  src/styles/colors.scss
  src/styles/header.scss
  src/styles/modals.scss
  src/styles/reset.scss
  src/styles/style.css
  src/styles/style.scss
Labels: enhancement

#11 cards updating implemented
  src/index.html
  src/js/CardModalUI.js
  src/js/CardUI.js
Labels: enhancement, review

#12 EventEmmiter added
  src/js/EventEmitter.js
Labels: enhancement, review

#13 getter and setter for username added
  src/js/AuthAPI.js
  src/js/User.js
Labels: enhancement, review

#14 Drag n drop implemented
  package-lock.json
  package.json
  src/js/CardUI.js
  src/js/ColumnUI.js
Labels: enhancement, review

#15 added loggedIn emitter
  src/index.html
  src/js/App.js
  src/js/AuthUI.js
  src/js/BoardUI.js
  src/js/SignInUI.js
  src/js/SignUpUI.js
Labels: enhancement, review

#17 global catch added
  src/js/User.js
  src/js/config.js
Labels: enhancement, review

#18 authEvent emitter, logout handler, reset fields in modals
  src/index.html
  src/js/AuthUI.js
  src/js/BoardUI.js
  src/js/SignInUI.js
  src/js/SignUpUI.js
  src/js/UserUI.js
Labels: enhancement, review

#19 submit form on key down
  src/index.html
  src/js/AddFormUI.js
  src/js/AuthUI.js
  src/js/CardModalUI.js
Labels: enhancement, review
